AWSTemplateFormatVersion: '2010-09-09'
Description: 'Blood Pressure Calculator - EC2 Infrastructure'

Parameters:
  ApplicationName:
    Type: String
    Default: bp-calculator-app
    Description: Name of the application

  KeyName:
    Type: String
    Default: bp-py
    Description: EC2 Key Pair name for SSH access

  VpcId:
    Type: String
    Default: vpc-0393d1315f5e64c75
    Description: VPC ID where the EC2 instance will be deployed

  SubnetId:
    Type: String
    Default: subnet-058dde5de2753fae4
    Description: Subnet ID where the EC2 instance will be deployed (must be in the specified VPC)

  InstanceType:
    Type: String
    Default: t2.micro
    Description: EC2 instance type (t2.micro is free tier eligible)
    AllowedValues:
      - t2.micro
      - t2.small
      - t2.medium

  LatestAmiId:
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: /aws/service/ami-amazon-linux-latest/al2023-ami-kernel-default-x86_64
    Description: Latest Amazon Linux 2023 AMI

Resources:
  # Security Group for EC2 Instance
  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for BP Calculator EC2 instance
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
          Description: Allow HTTP traffic
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
          Description: Allow SSH access
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0
          Description: Allow all outbound traffic
      Tags:
        - Key: Name
          Value: !Sub '${ApplicationName}-sg'

  # IAM Role for EC2 Instance
  InstanceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSXRayDaemonWriteAccess
        - arn:aws:iam::aws:policy/CloudWatchAgentServerPolicy
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
      Policies:
        - PolicyName: SecretsManagerAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                Resource: !Ref FlaskSecretKey
        - PolicyName: CloudWatchLogsAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                  - logs:DescribeLogStreams
                Resource: 'arn:aws:logs:*:*:*'
        - PolicyName: S3DeploymentAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:ListBucket
                Resource:
                  - 'arn:aws:s3:::bp-deploy-temp-*'
                  - 'arn:aws:s3:::bp-deploy-temp-*/*'

  # Instance Profile
  InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref InstanceRole

  # Secrets Manager for Flask Secret Key
  FlaskSecretKey:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub "${ApplicationName}-flask-secret-key"
      Description: Flask application secret key
      GenerateSecretString:
        SecretStringTemplate: "{}"
        GenerateStringKey: secret_key
        PasswordLength: 32
        ExcludeCharacters: '"@/\'

  # EC2 Instance
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref LatestAmiId
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyName
      IamInstanceProfile: !Ref InstanceProfile
      SubnetId: !Ref SubnetId
      SecurityGroupIds:
        - !Ref InstanceSecurityGroup
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          set -e
          
          # Update system
          yum update -y
          
          # Install Python 3.12 and required packages
          yum install -y python3.12 python3.12-pip git
          
          # Create app directory
          mkdir -p /opt/bp-calculator
          cd /opt/bp-calculator
          
          # Get SECRET_KEY from Secrets Manager
          SECRET_KEY=$(aws secretsmanager get-secret-value \
            --secret-id ${FlaskSecretKey} \
            --region ${AWS::Region} \
            --query SecretString \
            --output text | python3.12 -c "import sys, json; print(json.load(sys.stdin)['secret_key'])")
          
          # Create environment file
          cat > /opt/bp-calculator/.env << EOF
          FLASK_ENV=production
          SECRET_KEY=$SECRET_KEY
          CLOUDWATCH_ENABLED=true
          AWS_REGION=${AWS::Region}
          HOST=0.0.0.0
          PORT=80
          EOF
          
          # Create systemd service file
          cat > /etc/systemd/system/bp-calculator.service << 'EOF'
          [Unit]
          Description=BP Calculator Flask Application
          After=network.target
          
          [Service]
          Type=simple
          User=root
          WorkingDirectory=/opt/bp-calculator
          Environment="PATH=/usr/bin"
          EnvironmentFile=/opt/bp-calculator/.env
          ExecStart=/usr/bin/gunicorn --bind 0.0.0.0:80 --workers 4 --timeout 600 app:app
          Restart=always
          RestartSec=10
          
          [Install]
          WantedBy=multi-user.target
          EOF
          
          # Enable and start service (will fail initially until code is deployed)
          systemctl daemon-reload
          systemctl enable bp-calculator.service
          
          # Signal CloudFormation that instance is ready
          /opt/aws/bin/cfn-signal -e $? --stack ${AWS::StackName} --resource EC2Instance --region ${AWS::Region} || true
      Tags:
        - Key: Name
          Value: !Sub '${ApplicationName}-instance'
    CreationPolicy:
      ResourceSignal:
        Timeout: PT15M

Outputs:
  InstanceId:
    Description: EC2 Instance ID
    Value: !Ref EC2Instance
    Export:
      Name: !Sub '${AWS::StackName}-InstanceId'

  PublicDNS:
    Description: Public DNS name of the EC2 instance
    Value: !GetAtt EC2Instance.PublicDnsName
    Export:
      Name: !Sub '${AWS::StackName}-PublicDNS'

  PublicIP:
    Description: Public IP address of the EC2 instance
    Value: !GetAtt EC2Instance.PublicIp
    Export:
      Name: !Sub '${AWS::StackName}-PublicIP'

  ApplicationURL:
    Description: URL of the application
    Value: !Sub 'http://${EC2Instance.PublicDnsName}'

  SecretKeyArn:
    Description: ARN of the Flask secret key in Secrets Manager
    Value: !Ref FlaskSecretKey
    Export:
      Name: !Sub "${AWS::StackName}-SecretKeyArn"
